### PR TITLE
American Truck Simulator Support

### PR DESCRIPTION
**Pull request by mike-koch**
This PR adds support for American Truck Simulator.  The follow changes were made:

- Added a setup step for ATS, which will add the necessary DLL and add the necessary firewall rule / ACL rule
- Updated the uninstaller to uninstall both the ETS2 and ATS telemetry plugins
- The setup window will only show if both the ATS and ETS2 plugins are not installed
- Add a button to the main form to install the telemetry plugin (in case the user already has the ETS2 plugin installed but still needs to install the ATS plugin)
- Bumped the version number to 3.1.0

** Please note: ** some C# 6-specific syntax has been introduced in this pull request, which will require Visual Studio 2015 AFAIK (I was not able to open the .Mobile solution in VS 2013 (and I could not find the Cordova Tools for VS 2013; the website kept redirecting me to the VS 2015 download), so I had to update it to 2015 in order to open it).

### CODE REVIEW

**Comment by DimitriMayakovsky** [comment]
lol detected trojan kasperksy ;-;

**Comment by mike-koch** [comment]
What file?

**Comment by DimitriMayakovsky** [comment]
ets2telemetry.exe

**Comment by DimitriMayakovsky** [comment]
I send report to kaspersky for fix database ;]

**Comment by mike-koch** [comment]
Ya I ran the same analysis. `HEUR` means that it tried a "heuristic" analysis and it is making an educated guess as to its safe/unsafe state. I'll have to look into why it's detecting this false-positive.

**Comment by Funbit** [comment]
Absorbed by the latest server version (3.2.0).

**Pull request closed without merging**
